### ISSUE TITLE
Display historical forecast from best plan and user chosen plan in trend chart

### ISSUE THREAD

**Issue by kennysimsj** [indexhub-ai/indexhub#233]
## TODO:

- [ ] Add 2 additional lines into trend chart represent the best plan and user chosen plan for current run (read from `rolling_forecast.parquet`)
- [ ] Add 6 additional lines into trend chart represent the historical best plan and user chosen plan for past 3 runs (read from `rolling_forecast.parquet`)
- [ ] Allow to select/deselect lines from legend
