### ISSUE TITLE
feat: Add product quadrant table and chart

### ISSUE THREAD

**Issue by jasmineliaw** [indexhub-ai/indexhub#332]
### TODO:

- [x] Add `product_col`, `quantity_col`, and `value_col` into objective schema
- [x] Create a new router and endpoints for product quadrant table and chart
- [ ] FE: Select product column, quantity column, and value column from columns of selected dataset during objective creation (uncomment L382-394 in `schemas.py`)
- [ ] FE: Add new tab "Product Quadrant" after "Inventory Table" to display product quadrant table view and chart
- [ ] FE: Display message "Product quadrant not available for this objective" if endpoint `get_product_quadrant_table` returns None
